// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using microservice.SupplyAPI.Infrastructure.Database.Contexts;

#nullable disable

namespace microservice.SupplyAPI.Infrastructure.Database.Migrations
{
    [DbContext(typeof(SupplyDbContext))]
    [Migration("20251122203747_SupplyProductAddedQuantity")]
    partial class SupplyProductAddedQuantity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("microservice.SupplyAPI.Infrastructure.Database.Entities.DeliveryTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryType");
                });

            modelBuilder.Entity("microservice.SupplyAPI.Infrastructure.Database.Entities.SupplierEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DeliveryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("eliveryTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("eliveryTypeId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("microservice.SupplyAPI.Infrastructure.Database.Entities.SupplyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SupplyDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Supply");
                });

            modelBuilder.Entity("microservice.SupplyAPI.Infrastructure.Database.Entities.SupplyProductEntity", b =>
                {
                    b.Property<Guid>("SupplyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("SupplyId", "ProductId");

                    b.ToTable("SupplyProduct");
                });

            modelBuilder.Entity("microservice.SupplyAPI.Infrastructure.Database.Entities.SupplierEntity", b =>
                {
                    b.HasOne("microservice.SupplyAPI.Infrastructure.Database.Entities.DeliveryTypeEntity", "DeliveryType")
                        .WithMany()
                        .HasForeignKey("eliveryTypeId");

                    b.Navigation("DeliveryType");
                });

            modelBuilder.Entity("microservice.SupplyAPI.Infrastructure.Database.Entities.SupplyEntity", b =>
                {
                    b.HasOne("microservice.SupplyAPI.Infrastructure.Database.Entities.SupplierEntity", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("microservice.SupplyAPI.Infrastructure.Database.Entities.SupplyProductEntity", b =>
                {
                    b.HasOne("microservice.SupplyAPI.Infrastructure.Database.Entities.SupplyEntity", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supply");
                });
#pragma warning restore 612, 618
        }
    }
}
